version: '3'
services:
  db:
    image: postgres:13
    env_file:
      - .env
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES__USER}
      - POSTGRES_PASSWORD=${POSTGRES__PASSWORD}
      - POSTGRES_DB=${POSTGRES__DBNAME}
    depends_on:
      - service
    ports:
      - 5432:5432