version: '3'
services:
  db:
    image: postgres:13
    restart: always
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: qwe
      POSTGRES_USER: app
      POSTGRES_DB: notifications
    depends_on:
      - service
    ports:
      - 5432:5432