# Generated by Django 4.1.6 on 2023-02-07 08:27

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("id_user", models.UUIDField()),
                ("email", models.EmailField(max_length=255, null=True)),
                ("message", models.TextField(null=True)),
                ("event", models.CharField(max_length=255)),
                ("priority", models.IntegerField(null=True)),
            ],
            options={
                "db_table": "event",
            },
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("crontab", models.CharField(max_length=50)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "schedule",
            },
        ),
        migrations.CreateModel(
            name="Template",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("html", models.TextField()),
                ("event_name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "db_table": "template",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
            options={
                "db_table": "user",
            },
        ),
        migrations.AddIndex(
            model_name="template",
            index=models.Index(
                fields=["event_name"], name="template_event_n_980214_idx"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="id_schedule",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="admin_panel.schedule",
            ),
        ),
    ]
