# Generated by Django 4.1.6 on 2023-02-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_panel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="characteristic",
            field=models.ManyToManyField(
                through="admin_panel.UserCharacteristic",
                to="admin_panel.characteristic",
            ),
        ),
    ]
