name: Code Sanity Check and Mypy

on:
  push:
    branches: [main, dev-zelenov-test]
  pull_request:
    branches: [main, dev-zelenov-test]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SQLALCHEMY_SILENCE_UBER_WARNING: 1
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install -r notifications_service/dev.requirements.txt

      - name: Run sanity check
        run: |
          python -m pytest notifications_service/tests/functional/src/

      - name: Run mypy
        run: |
          pip install mypy
          mypy --ignore-missing-imports notifications_service/src/

      - name: send failure telegram message
        if: ${{ failure() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.QA_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_API_TOKEN }}
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
            Repository: ${{ github.repository }}
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}

      - name: send success telegram message
        if: ${{ success() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.QA_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_API_TOKEN }}
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
            Repository: ${{ github.repository }}
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
