name: Code Sanity Check and Mypy

on:
  push:
    branches: [ "dev-zelenov-ci", "main" ]
  pull_request:
    branches: [ "dev-zelenov-ci", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.8, 3.9 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install -r notifications_service/requirements.txt

      - name: Run sanity check
        run: |
          python3 -m pytest notifications_service/tests/functional/src/

      - name: Run mypy
        run: |
          mypy --ignore-missing-imports notifications_service/src

      - name: Send notification
        if: failure()
        env:
          TELEGRAM_API_TOKEN: ${{ secrets.TELEGRAM_API_TOKEN }}
          CHAT_ID: ${{ secrets.QA_CHAT_ID }}
          TESTS: ${{ job.status }}
          FAILED_STEP_NAME: ${{ job.steps[3].name }}
        run: |
          pip install python-telegram-bot
          pip install gitpython
          python .github/tools/send_message.py ${TELEGRAM_API_TOKEN} ${CHAT_ID} ${TESTS} ${FAILED_STEP_NAME} "Code Sanity Check and Mypy failed!"

      - name: Send notification
        if: success()
        env:
          TELEGRAM_API_TOKEN: ${{ secrets.TELEGRAM_API_TOKEN }}
          CHAT_ID: ${{ secrets.QA_CHAT_ID }}
          TESTS: ${{ job.status }}
        run: |
          pip install python-telegram-bot
          pip install gitpython
          python .github/tools/send_message.py ${TELEGRAM_API_TOKEN} ${CHAT_ID} ${TESTS} "Code Sanity Check and Mypy failed!"
